version: '2'

services:
  mariadb:
    image: 'mariadb:latest'
    environment:
      - MYSQL_USER=bn_testlink
      - MYSQL_DATABASE=bitnami_testlink
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    ports:
    - '3307:3306'
    restart: always
    volumes:
      - 'mariadb_data:/bitnami'
  testlink:
    image: 'docker.io/bitnami/testlink:latest'
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - TESTLINK_DATABASE_USER=bn_testlink
      - TESTLINK_DATABASE_NAME=bitnami_testlink
      - ALLOW_EMPTY_PASSWORD=yes
      - APACHE_HTTP_PORT_NUMBER=8080
      - APACHE_HTTPS_PORT_NUMBER=8143
    ports:
      - '8082:8080'
      - '8143:8143'
    volumes:
      - 'testlink_data:/bitnami'
    depends_on:
      - mariadb

volumes:
  mariadb_data:
    driver: local
  testlink_data:
    driver: local